### ISSUE TITLE
Vurder å legge til gruppebeskrivelse på "about us" siden. 

### ISSUE THREAD

**Issue by imttv** [JosteinEng/IS-310#11]
Se tittel

**Comment by JosteinEng** [comment]
Stjal bare et avsnitt fra om oss siden

"Studentgruppen som representerer gruppe 9 har over flere semestere jobbet delaktig sammen for å utarbeide gode resultater og lærdom gjennom bachelorprogrammet, IT og Informasjonssystemer ved UiA. Gjennom studiene har studentene bygget god faglig kompetanse på både individuelt plan, og i felleskap. Gruppen har sammen utarbeidet en arbeidsdynamikk som effektivt tar i bruk enkeltpersoners evner, erfaringer, styrker og svakheter, for å skape et arbeidsmiljø som er inkluderende og effektivt ved prosjektgjennomføring og arbeid. Denne sammensetningen skaper rom for åpenhet, troverdighet og utfyllelse ved hverandres evner, tanker og ønsker ved et gitt arbeid."


funker det?
